"""add estimated minutes to tasks

Revision ID: 3f687a9286f1
Revises: f0cfbbeaca2f
Create Date: 2026-07-24 14:30:31.555628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f687a9286f1'
down_revision: Union[str, Sequence[str], None] = 'f0cfbbeaca2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'estimated_minutes')
    # ### end Alembic commands ###
